apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zpb26my8z-go 
  janus-idp.io/tekton: zpb26my8z-go
  backstage.io/kubernetes-id: zpb26my8z-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zpb26my8z-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  