apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zpb26my8z-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zpb26my8z-go 
  name: zpb26my8z-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zpb26my8z-go 
